name: Basic Deploy Test

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    environment: defualt

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Connect to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            
            cd /home/ubuntu/Ecommerce-Website-Java
            git pull origin main

            cd /home/ubuntu/Ecommerce-Website-Java/backend
            mvn clean package -DskipTests

            pkill -f 'target/ecommerce-backend-1.0.0.jar' || true || true

            nohup java -jar target/*.jar \
              --server.address=0.0.0.0 \
              --server.port=8080 \
              --spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce \
              > backend.log 2>&1 &
